### ISSUE TITLE
Latest flask version doesn't work with pinned flask-session==0.3.2

### ISSUE THREAD

**Issue by grischard** [XeroAPI/xero-python-oauth2-starter#37]
If you get

`AttributeError: 'Flask' object has no attribute 'session_cookie_name'`

then simply

`pip install --upgrade flask-session flask-oauthlib`

**Comment by laplandlearner** [comment]
blinker==1.8.1
cachelib==0.13.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
Flask==3.0.3
Flask-OAuthlib==0.9.6
Flask-Session==0.8.0
idna==3.7
itsdangerous==2.2.0
Jinja2==3.1.4
MarkupSafe==2.1.5
msgspec==0.18.6
oauthlib==2.1.0
python-dateutil==2.9.0.post0
requests==2.31.0
requests-oauthlib==1.1.0
six==1.16.0
urllib3==2.2.1
Werkzeug==3.0.3
xero_python==1.5.3

**Comment by jmanecke** [comment]
Is the best way to solve this to pin to older and older versions? This is a simple starter app just to illustrate concepts.

xero_python==1.5.3 is from 2021 and it is now on 7.x versions, why are we pinned to that?

I feel taking all the pins off the original requirements.txt is a better approach, or at least make them much more flexible. It's not the app that has changed, its the dependencies that have moved on.

**Comment by jmanecke** [comment]
Added a PR to just remove the pinned versions. That seems like the simplest way to solve this issue. It also has a greater likelihood of continuing to work over time as versions change.
